### ISSUE TITLE
multithreading

### ISSUE THREAD

**Issue by alexjironkin** [nickjcroucher/gubbins#151]
Hi,

I was wondering if there is multithreaded/MPI version of gubbins?

**Comment by tseemann** [comment]
It has a `--num_threads` option.

**Comment by alexjironkin** [comment]
I found `--threads`, but thats for RAxML according to the help of `run_gubbins.py`. What script takes `--num_threads`?

**Comment by andrewjpage** [comment]
Hi Alex,
The majority of the compute time is spent running RAxML, hence the --threads parameter.  If you have the AVX version of RAxML installed, it will run substantially faster than the default. The core gubbins algorithm uses only a tiny amount of compute so parallelising that part isnt on the cards since there would be no noticeable speedup.
Andrew
