### ISSUE TITLE
not enough mem

### ISSUE THREAD

**Issue by hildebra** [nickjcroucher/gubbins#190]
Dear Sir,
I get the follwing error when I run gubbins, on a dataset that includes a lot of "N" 's (more than 25%). it acorts withi this message:
Failed while running Gubbins. Please ensure you have enough free memory
Gubbins run finished

which I thuink is unlinkely since I run gubbins on a server with 256G of ram and from ""top" it seems that not even a fraction of this is being used. If I remove the sequences by hand that contain lots of N's or filter with gubbins for 25%, the run finishes. Note that I set and would like to use the "--filter_percentage 95" flag.
Any help would be very welcome.
best, Falk Hildebrand

**Comment by tseemann** [comment]
What do the "N" characters represent?

**Comment by hildebra** [comment]
Hey, the N are unknown Nucleotides in the alignment - basically regions where I don't have enough coverage, since this was an alignment of short reads to the reference genome. Additionally, I also have "-" characters in the "alignments" where I do not even have 1 coverage, probably the majority of missing data is actually represented with "-" characters.

**Comment by andrewjpage** [comment]
Hi Falk,
You are correct that this is not a memory error. One of the underlying programs has crashed due to the data provided. It looks like you have answered your own query, the algorithm will fundamentally not work with sequences where there is a vast amount of missing data. There are a few other methods though you could try which might work better with missing data such as FastGear, ClonalFrameML, BratNextGen, or PHEnix.
Regards,
Andrew

**Comment by hildebra** [comment]
Ok, thanks a lot Andrew.
