### ISSUE TITLE
Make the FTP urls actual hyperlinks

### ISSUE THREAD

**Issue by tseemann** [nickjcroucher/gubbins#229]
https://github.com/sanger-pathogens/gubbins#data-from-the-paper

to ease downloading.

**Comment by puethe** [comment]
You are right, but I'm afraid github doesn't support links to ftp sites, see also the discussion [here](https://github.com/jekyll/jekyll/issues/373) and the following [example](https://github.com/eedeebee/github-markdown-ftp-bug). Unless you happen to know a trick, I'll close this due to being a github issue.

**Comment by tseemann** [comment]
Hmm. that's annoying!  thanks for replying.
