### ISSUE TITLE
Specify OutPut Path or Tmp

### ISSUE THREAD

**Issue by Nilad** [nickjcroucher/gubbins#263]
I re-up this closed thread https://github.com/sanger-pathogens/gubbins/issues/209

I work with singularity image and the compartiment of files is a major problem. Can you add path for output file or better a tmp file path ?

Thanks in advance.

**Comment by Nilad** [comment]
I see that with the `-p` option, i can rooted the output files if absolut path is provided.

But only one file is not rooted -> `core_gene_alignment.aln.seq.joint.txt`

Maybe, it could be a nice thing to make an option for an output directory in the python/gubbins/common.py script ( especialy for the files paths defines in lines 103-112).

**Comment by puethe** [comment]
Hi @Nilad ,
which version of Gubbins are you using? I remember there was an issue with the prefix not being added to all output files, but that should be fixed in the most recent version (2.4.0).
We do not really maintain Gubbins anymore, so I'm afraid that your suggestion won't be addressed any time soon, but if it's important to you feel free to submit a pull request.
Cheers,
Christoph

**Comment by Nilad** [comment]
Hi @puethe,
You have right, i used a previous version `2.3.4` and now with the `2.4.0` i dont have the file root problem.

Its a good idea to make a pull request. But it will not just for an "output directory option" but more to render Gubbins containerable for Docker/Singularity.
