### ISSUE TITLE
Gubbins with masked input alignment

### ISSUE THREAD

**Issue by nicolettacommins** [nickjcroucher/gubbins#275]
I'm trying to use Gubbins but want to mask certain regions in my analysis. For example, I want to exclude regions of the genome that tend to have issues with repetitiveness/mapping quality. My current strategy is to mask those regions, and then give a masked alignment to Gubbins.

I worry that masking many shorter regions in my input alignment will cause Gubbins to miss recombinations. However, I'm not sure how to mask the "bad" regions after running Gubbins. 

Does anyone have a good solution to this? Or is it ok to give Gubbins an input alignment with some regions already masked?

**Comment by tseemann** [comment]
`bedtools maskfasta`

**Comment by matbeale** [comment]
Or https://github.com/sanger-pathogens/remove_blocks_from_aln. 

You can give gubbins a masked alignment (sites masked to 'N'), depending on what your end goal is. Do you want gubbins to infer recombining sites because you are actually interested in the actual recombination, in which case masking before is probably not appropriate because it will miss things (and there may be better tools than gubbins in any case). If your goal is simply to mask out the recombination for downstream phylogeny, then as far as I am aware, it's unlikely to make a big impact on gubbins' ability to detect additional blocks, unless they are in close proximity to your masked regions.

In terms of when to mask, the default output of gubbins is a masked SNP alignment (the polymorphic_sites.fasta file), and that's a bit difficult to strip other sites from (because the positions have changed). Alternatively, you can reconstruct the masked WGS alignment (doable from the gff/embl files, but no script included with the package).
