### ISSUE TITLE
Using Gubbins on bactsnp resutls

### ISSUE THREAD

**Issue by roxmila** [nickjcroucher/gubbins#282]
I'm trying to understand how the gubbins software works based on results obtained with bactsnp. I wanted to test with a bacterial genome, CP025268.1 (knowing that I have to do this on 10 genomes) to be precise and I used the pseudo genome created by bactsnp as input for gubbins because it can also take a FASTA alignment file. But when I run gubbins I get this error:

"Error with input FASTA file: you need more than 3 sequences to build a meaningful tree. Each sequence must have a name and some genomic data. There input alignment file does not exist or has an invalid format"

While searching I saw that my alignment file contained only one line beginning with '>' while in the test file of example gubbins there are 11 of them numbered like that:

"PMEN1.aln:>2682
PMEN1.aln:>1731
PMEN1.aln:>1788
PMEN1.aln:>3350
PMEN1.aln:>3355
PMEN1.aln:>1842
PMEN1.aln:>2097
PMEN1.aln:>2098
PMEN1.aln:>1789
PMEN1.aln:>2699
PMEN1.aln:>3267
"

PMEN1 is an S pneumoniae and the numbers are its isolates. 
I've already align my complete genome of e coli strains to my reference genome (k12) and I planned to launch gubbins on it but not sure how to proceed, I'm missing something, can you help me? Thank you in advance.

**Comment by matbeale** [comment]
Hi,

Please excuse me if I'm misunderstanding you, but it sounds like you are trying to run gubbins on a single genome? You also say that your alignment file contains only one sequence header line beginning with '>' - i.e. only one sequence in the file. Gubbins must be run on a multiple sequence alignment of many samples - this is how it identifies recombination. You need to make a multiple sequence alignment of all your genomes in fasta format as input to gubbins. 

I should also note that unless your samples are _very_ closely related (e.g. same ST), gubbins is unlikely to be of much use for analysing E. coli because of the deep branching population structure typical in that species. 

BW,
Mat
