### ISSUE TITLE
Input file for gubbins

### ISSUE THREAD

**Issue by npbhavya** [nickjcroucher/gubbins#285]
Hi, 

For the input dataset for Gubbins, does the order of the genes in the multiple sequence alignment matter? Are there any assumptions about the alignment file that Gubbins is making to predict the recombination sites,  such that the genes analyzed should all belong to a specific lineage? 

We also made note that the Roary output should not be used as the input for this program, but if Roary was run only for a specific lineage of microbes, can the core gene alignment from Roary be provided as input? 

Thank You,

**Comment by matbeale** [comment]
Gene order does not matter 'per se', but you cannot use a concatenated gene alignment such as the one Roary would output. This is because the way Gubbins infers recombination is based on the position of SNPs in the genome (SNP density), so if you have concatenated genes together that is creating an artificial genome, with SNP densities that don't reflect the genome structure. This is true whether you are doing a species level phylogeny (something Gubbins is unsuited for in almost any circumstance, since it is designed for inferring within-cluster recombination), or a clade/lineage level phylogeny

**Comment by npbhavya** [comment]
Thank you!
