### ISSUE TITLE
What are the differences of the output trees made by gubbins

### ISSUE THREAD

**Issue by andreaniml** [nickjcroucher/gubbins#314]
Hello! Sorry if this is a silly question

When you run gubbins with a support flag (bootstrap, tbe or sh test) it generates three trees, taking the example dataset and a command line I saw in another issue:
`run_gubbins.py --first-tree-builder fasttree --first-model JC --tree-builder fasttree --model JC --bootstrap 100 --transfer-bootstrap --verbose ST239.aln`
I get:
(1) ST239.final_bootstrapped_tree.tre 
(2) ST239.final_tree.tre  
(3) ST239.node_labelled.final_tree.tre

(2) and (3) seem to be identical, however (1) Shows the same relationships, but apparently has a polytomy and the scale bar is larger on bootstrapped_tree (as seen on FigTree)

Why does this happen? If I wanted to make a dated phylogeny using BactDating, which tree should I use? Would there be significant differences?
Print of Figtree with side to side comparison:
![image](https://user-images.githubusercontent.com/58482628/138202870-28461edd-98f5-40d2-bc65-853f13a4d35f.png)

Thanks for any answers!

**Comment by nickjcroucher** [comment]
Hi @andreaniml - there are two separate issues here. Firstly, the two trees you show are topologically identical - that with bootstraps is unrooted, because it's not informative to calculate the bootstrap of a root node - you can midpoint root the bootstrapped tree with CTLR/Command+M in FigTree to see this. Hence either should converge towards the same result in BactDating.

However, the different scale bars are not expected, good spot - it turns out, this is a difference between annotating a tree with bootstrap support with RAxML or RAxML-NG. I do not understand what RAxML-NG is doing in this case, so I have switched the annotation back to RAxML in 75c30c1648b9f40aa398852c199170536a26192e. I'll release this as v3.1.3.

**Comment by andreaniml** [comment]
I see! Thanks for the quick answer, @nickjcroucher!
I've installed gubbins using conda, I guess it's better to ask it to run on RAxML using `--tree-builder raxml` for now then?

If It helps in any way, when I used sh support on my own data it had an enormous difference in the scale bar:

to the left is the "SH_support_tree",  and to the right it's the "final_tree"
![image](https://user-images.githubusercontent.com/58482628/138234149-91ca0a6f-0395-49c0-90c1-fac3b7b6c4fa.png)

**Comment by nickjcroucher** [comment]
The SH test trees are generally have branch lengths rescaled to substitutions per site, rather than substitutions; I noticed this earlier, and will see if I can fix this.

**Comment by nickjcroucher** [comment]
I have enquired about the difference in RAxML bootstrap trees in https://groups.google.com/g/raxml/c/qkWnw4p6-y0.

**Comment by nickjcroucher** [comment]
The RAxML team have replied to the enquiry above and pointed out the trees are identical - the root is just shifted along the same branch in a way that is tricky to interpret using standard Newick-formatted trees, as described in https://academic.oup.com/mbe/article/34/6/1535/3077051?login=true - so it's fine to keep using the RAxML-NG output.

**Comment by nickjcroucher** [comment]
SH values transferred onto the final tree in v3.1.3
