### ISSUE TITLE
gubbins 3.1.4 bioconda

### ISSUE THREAD

**Issue by annarerra** [nickjcroucher/gubbins#324]
Hello,

I was wondering when the new version of gubbins will be available in bioconda.

Thank you in advance :)

**Comment by nickjcroucher** [comment]
I hadn't noticed bioconda hadn't automatically updated, as it usually does, probably because the dependencies have changed. I've tried updating the conda recipe now, but it seems there is a problem merging into bioconda at the moment: https://github.com/bioconda/bioconda-recipes/actions/workflows/AutoMerge.yml. I'll let you know when I hear back.

**Comment by nickjcroucher** [comment]
You can still download the latest version of the repo and install that, using the instructions on the main page, if helpful.

**Comment by annarerra** [comment]
Thank you for the reply.
I do not have rights to install in the server and the people that do prefer the bioconda installation, so I will just wait.
And if you have any news, let me know..

Thank you again :)

**Comment by nickjcroucher** [comment]
v3.1.4 now available on bioconda
