### ISSUE TITLE
Tree only shows part of the isolates

### ISSUE THREAD

**Issue by tbazilegith** [nickjcroucher/gubbins#376]
Hi Nick,
I ran Gubbins on an alignment file of 56 isolates. However the tree tips from phandango visualization only displayed 26 isolates.
Any ideas about what might have happened?
Command used:
generate_ska_alignment.py --reference Lp_refseq.fasta --input all_strains_isolates.list --out lp_allstrains03.aln 
run_gubbins.py --prefix lp_allstrains lp_allstrains03.aln
- I used grep on the alignment file, and all 56 samples showed.
grep -c ">" aln_dir/lp_allstrains03.aln
56
Thanks,
TJ

**Comment by nickjcroucher** [comment]
Did any isolates get filtered out because of low coverage in the alignment?

________________________________
From: Tassy J. Bazile ***@***.***>
Sent: Wednesday, July 5, 2023 9:55:12 PM
To: nickjcroucher/gubbins ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nickjcroucher/gubbins] Tree only shows part of the isolates (Issue #376)


Hi Nick,
I ran Gubbins on an alignment file of 56 isolates. However the tree tips from phandango visualization only displayed 26 isolates.
Any ideas about what might have happened?
Command used:
generate_ska_alignment.py --reference Lp_refseq.fasta --input all_strains_isolates.list --out lp_allstrains03.aln
run_gubbins.py --prefix lp_allstrains lp_allstrains03.aln

  *   I used grep on the alignment file, and all 56 samples showed.
grep -c ">" aln_dir/lp_allstrains03.aln
56
Thanks,
TJ

**Comment by tbazilegith** [comment]
I have used no filter - does Gubbins automatically filter alignments?

**Comment by nickjcroucher** [comment]
Yes (see https://github.com/nickjcroucher/gubbins/blob/master/docs/gubbins_manual.md for further details):

`  --filter-percentage FILTER_PERCENTAGE, -f FILTER_PERCENTAGE
                        Filter out taxa with more than this percentage of gaps (default: 25.0)`

This would suggest your query sequence may be too divergent from your reference (if it is the solution).

**Comment by tbazilegith** [comment]
Thanks Nick for the recommendation. I think you're right.
I looked some of the missing samples closer by running Gubbins on them separately. My log file showed this
Excluded sequence GCF_003003515_1_ASM300351v1 because it had 32.67690693746764 percentage missing data while a maximum of 25.0 is allowed
Excluded sequence GCF_003003535_1_ASM300353v1 because it had 33.92725153635454 percentage missing data while a maximum of 25.0 is allowed
Excluded sequence GCF_003003555_1_ASM300355v1 because it had 33.92753691845549 percentage missing data while a maximum of 25.0 is allowed
Excluded sequence GCF_003004195_1_ASM300419v1 because it had 32.020299799604686 percentage missing data while a maximum of 25.0 is allowed
Excluded sequence GCF_003004235_1_ASM300423v1 because it had 30.16437438250448 percentage missing data while a maximum of 25.0 is allowed
Excluded sequence GCF_003004335_1_ASM300433v1 because it had 34.4350604467828 percentage missing data while a maximum of 25.0 is allowed
- Do you think allowing a greater percentage is good idea? Like --filter-percentage 37? May be finding another reference for the aln?
Thanks

**Comment by nickjcroucher** [comment]
I would find a more closely-related reference, definitely.

________________________________
